/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.tiglass.invoices.forms;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.security.cert.X509Certificate;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.security.auth.x500.X500Principal;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import mx.bigdata.sat.security.KeyLoaderEnumeration;
import mx.bigdata.sat.security.factory.KeyLoaderFactory;
import net.tiglass.invoices.connection.SqlConnection;
import net.tiglass.invoices.properties.AppProperties;
import net.tiglass.invoices.wsclient.ServiceClient;
import sun.security.x509.RDN;
import sun.security.x509.X500Name;

/**
 *
 * @author TIGLASS 2
 */
public class frmAdministration extends javax.swing.JFrame {

    private AppProperties properties = new AppProperties();
    OutputStream salida = null;

    /**
     * Creates new form frmAdministration
     */
    public frmAdministration() {
        initComponents();

        try {
            //loadProperties();
            checkExistsProperties();
            loadDataBaseInfo();
            loadCertInfo();
        } catch (Exception ex) {
            //java.util.logging.Logger.getLogger(frmAdministration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanelPrincipal = new javax.swing.JTabbedPane();
        pnlOrigenDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBaseDatos = new javax.swing.JTextField();
        txtInstancia = new javax.swing.JTextField();
        txtServidor = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        btnProbarConexionBD = new javax.swing.JButton();
        pnlComprobantes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNumeroSerie = new javax.swing.JLabel();
        lblEnviadoA = new javax.swing.JLabel();
        lblEmitidoPor = new javax.swing.JLabel();
        lblVigencia = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDireccionServicio = new javax.swing.JTextField();
        txtConstanciasRetenciones = new javax.swing.JTextField();
        btnProbarConexion = new javax.swing.JButton();
        txtContrasenaToken = new javax.swing.JPasswordField();
        chkCancelarSAT = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtConstanciasRetencionesCancelar = new javax.swing.JTextField();
        txtDireccionServicioCancelar = new javax.swing.JTextField();
        btnProbarConexionCancelar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtRutaCertificado = new javax.swing.JTextField();
        btnExaminarCertificado = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtRutaLlave = new javax.swing.JTextField();
        btnExaminarLlave = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtContrasenaLlave = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        txtRutaCFDs = new javax.swing.JTextField();
        btnExaminarRutaCFDs = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        cboTipoPersona = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        cboRegimen = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        txtUsuarioWsTimbrado = new javax.swing.JTextField();
        chkRutaCFD = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración");
        setResizable(false);

        jLabel1.setText("Servidor:");

        jLabel2.setText("Instancia:");

        jLabel3.setText("Base de datos:");

        jLabel4.setText("Usuario:");

        jLabel5.setText("Contraseña:");

        btnProbarConexionBD.setText("Probar conexión");
        btnProbarConexionBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbarConexionBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOrigenDatosLayout = new javax.swing.GroupLayout(pnlOrigenDatos);
        pnlOrigenDatos.setLayout(pnlOrigenDatosLayout);
        pnlOrigenDatosLayout.setHorizontalGroup(
            pnlOrigenDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrigenDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrigenDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProbarConexionBD)
                    .addGroup(pnlOrigenDatosLayout.createSequentialGroup()
                        .addGroup(pnlOrigenDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(pnlOrigenDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(txtBaseDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(txtInstancia, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(txtServidor, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(txtContrasena))))
                .addContainerGap(515, Short.MAX_VALUE))
        );

        pnlOrigenDatosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBaseDatos, txtInstancia, txtServidor, txtUsuario});

        pnlOrigenDatosLayout.setVerticalGroup(
            pnlOrigenDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrigenDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrigenDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrigenDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtInstancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrigenDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBaseDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrigenDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrigenDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProbarConexionBD)
                .addContainerGap(397, Short.MAX_VALUE))
        );

        tabPanelPrincipal.addTab("Origen de datos", pnlOrigenDatos);

        jLabel6.setText("Certificado");

        jLabel7.setText("Número de serie:");

        jLabel8.setText("Enviado a:");

        jLabel9.setText("Emitido por:");

        jLabel10.setText("Vigencia:");

        lblNumeroSerie.setText("jLabel11");

        lblEnviadoA.setText("jLabel11");

        lblEmitidoPor.setText("jLabel11");

        lblVigencia.setText("jLabel11");

        jLabel11.setText("Servicio de certificación CFDI");

        jLabel12.setText("Dirección del servicio:");

        jLabel13.setText("Constancias retenciones:");

        jLabel14.setText("Contraseña (token):");

        btnProbarConexion.setText("Probar conexión");
        btnProbarConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbarConexionActionPerformed(evt);
            }
        });

        chkCancelarSAT.setText("Cancelar CFDI directamente en el SAT");

        jLabel15.setText("Dirección del servicio:");

        jLabel16.setText("Constancias retenciones:");

        btnProbarConexionCancelar.setText("Probar conexión");

        jLabel17.setText("Certificado de sellos digitales:");
        jLabel17.setToolTipText("Certificado de sellos digitales:");

        btnExaminarCertificado.setText("Examinar");
        btnExaminarCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarCertificadoActionPerformed(evt);
            }
        });

        jLabel18.setText("Llave privada:");
        jLabel18.setToolTipText("");

        btnExaminarLlave.setText("Examinar");
        btnExaminarLlave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarLlaveActionPerformed(evt);
            }
        });

        jLabel19.setText("Contraseña:");
        jLabel19.setToolTipText("");

        btnExaminarRutaCFDs.setText("Examinar");
        btnExaminarRutaCFDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarRutaCFDsActionPerformed(evt);
            }
        });

        jLabel21.setText("Régimen fiscal de la empresa");

        jLabel22.setText("Tipo de persona:");

        cboTipoPersona.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Moral", "Fisica" }));

        jLabel23.setText("Régimen:");

        cboRegimen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Régimen general personas morales", "Régimen de las personas morales con fines no lucrativos" }));

        jLabel24.setText("Usuario:");

        chkRutaCFD.setText("Ruta CFDs:");
        chkRutaCFD.setToolTipText("Se usa la ruta del alfak de manera predeterminada. Seleccionar para establecer una nueva ruta.");
        chkRutaCFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRutaCFDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlComprobantesLayout = new javax.swing.GroupLayout(pnlComprobantes);
        pnlComprobantes.setLayout(pnlComprobantesLayout);
        pnlComprobantesLayout.setHorizontalGroup(
            pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComprobantesLayout.createSequentialGroup()
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlComprobantesLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEnviadoA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeroSerie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmitidoPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVigencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlComprobantesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5))
                    .addGroup(pnlComprobantesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlComprobantesLayout.createSequentialGroup()
                                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24)
                                    .addComponent(chkRutaCFD)
                                    .addGroup(pnlComprobantesLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboTipoPersona, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDireccionServicio)
                                    .addComponent(txtConstanciasRetenciones, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                                    .addComponent(txtDireccionServicioCancelar)
                                    .addComponent(txtConstanciasRetencionesCancelar)
                                    .addComponent(cboRegimen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRutaLlave, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                                    .addComponent(txtRutaCertificado)
                                    .addComponent(txtRutaCFDs)
                                    .addGroup(pnlComprobantesLayout.createSequentialGroup()
                                        .addComponent(txtContrasenaLlave, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 312, Short.MAX_VALUE))
                                    .addGroup(pnlComprobantesLayout.createSequentialGroup()
                                        .addComponent(txtUsuarioWsTimbrado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtContrasenaToken, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnProbarConexionCancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnProbarConexion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnExaminarLlave, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnExaminarCertificado, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnExaminarRutaCFDs, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(pnlComprobantesLayout.createSequentialGroup()
                                .addComponent(chkCancelarSAT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3))
                            .addGroup(pnlComprobantesLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2))
                            .addGroup(pnlComprobantesLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1))
                            .addComponent(jSeparator4))))
                .addGap(21, 21, 21))
        );
        pnlComprobantesLayout.setVerticalGroup(
            pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComprobantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtRutaCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExaminarLlave))
                .addGap(7, 7, 7)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtRutaLlave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExaminarCertificado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtContrasenaLlave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblNumeroSerie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblEnviadoA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblEmitidoPor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblVigencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDireccionServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProbarConexion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtConstanciasRetenciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtContrasenaToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(txtUsuarioWsTimbrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkCancelarSAT)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtDireccionServicioCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProbarConexionCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtConstanciasRetencionesCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cboTipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboRegimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlComprobantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutaCFDs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExaminarRutaCFDs)
                    .addComponent(chkRutaCFD))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        tabPanelPrincipal.addTab("Comprobantes fiscales digitales", pnlComprobantes);

        btnGuardar.setText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanelPrincipal)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            SaveDataBaseInfo();
            SaveCertInfo();
            loadCertInfo();
            btnGuardar.setEnabled(false);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnExaminarLlaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarLlaveActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            FileNameExtensionFilter fExtension = new FileNameExtensionFilter("*.cer", "cer");
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.setFileFilter(fExtension);
            int selection = fc.showOpenDialog(fc);

            if (selection == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                txtRutaCertificado.setText(file.getAbsolutePath());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnExaminarLlaveActionPerformed

    private void btnExaminarCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarCertificadoActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            FileNameExtensionFilter fExtension = new FileNameExtensionFilter("*.key", "key");
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.setFileFilter(fExtension);
            int selection = fc.showOpenDialog(fc);

            if (selection == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                txtRutaLlave.setText(file.getAbsolutePath());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnExaminarCertificadoActionPerformed

    private void btnExaminarRutaCFDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarRutaCFDsActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            //FileNameExtensionFilter fExtension = new FileNameExtensionFilter("*.key","key");
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            //fc.setFileFilter(fExtension);
            int selection = fc.showOpenDialog(fc);

            if (selection == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                txtRutaCFDs.setText(file.getAbsolutePath());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnExaminarRutaCFDsActionPerformed

    private void btnProbarConexionBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbarConexionBDActionPerformed
        try {
            SaveDataBaseInfo();
            SqlConnection connection = new SqlConnection();
            JOptionPane.showMessageDialog(rootPane, "Conexión establecida correctamente!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al intentar establecer la conexión con el origen de datos. " + ex);
        }
    }//GEN-LAST:event_btnProbarConexionBDActionPerformed

    private void btnProbarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbarConexionActionPerformed
        ServiceClient wsClient = new ServiceClient();

        if (wsClient.existeConexionCD(txtDireccionServicio.getText() + "?wsdl")) {
            JOptionPane.showMessageDialog(rootPane, "Conexión establecida correctamente!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error al intentar establecer la conexión.");
        }
    }//GEN-LAST:event_btnProbarConexionActionPerformed

    private void chkRutaCFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRutaCFDActionPerformed
        if (chkRutaCFD.isSelected()) {
            txtRutaCFDs.setEnabled(true);
            btnExaminarRutaCFDs.setEnabled(true);
            properties.setProperty("chkRutaCFD", "true");
        } else {
            txtRutaCFDs.setEnabled(false);
            btnExaminarRutaCFDs.setEnabled(false);
            properties.setProperty("chkRutaCFD", "false");
        }
    }//GEN-LAST:event_chkRutaCFDActionPerformed

    public void loadDataBaseInfo() {
        txtServidor.setText(properties.getProperty("server"));
        txtInstancia.setText(properties.getProperty("instance"));
        txtBaseDatos.setText(properties.getProperty("database"));
        txtUsuario.setText(properties.getProperty("user"));
        txtContrasena.setText(properties.getProperty("password"));
    }

    public void SaveDataBaseInfo() throws FileNotFoundException, IOException {
        properties.setProperty("server", txtServidor.getText());
        properties.setProperty("instance", txtInstancia.getText());
        properties.setProperty("database", txtBaseDatos.getText());
        properties.setProperty("user", txtUsuario.getText());
        properties.setProperty("password", new String(txtContrasena.getPassword()));
    }

    public void SaveCertInfo() throws FileNotFoundException, IOException {
        properties.setProperty("cerPath", txtRutaCertificado.getText());
        properties.setProperty("keyPath", txtRutaLlave.getText());
        properties.setProperty("keyPass", new String(txtContrasenaLlave.getPassword()));

        properties.setProperty("servCfdiPath", txtDireccionServicio.getText());
        properties.setProperty("servRetPath", txtConstanciasRetenciones.getText());
        properties.setProperty("servCfdiUser", txtUsuarioWsTimbrado.getText());
        properties.setProperty("servCfdiPass", new String(txtContrasenaToken.getPassword()));

        if (chkCancelarSAT.isSelected()) {
            properties.setProperty("cancelCfdiSat", "true");
        } else {
            properties.setProperty("cancelCfdiSat", "false");
        }

        properties.setProperty("cancelServCfdiPath", txtDireccionServicioCancelar.getText());
        properties.setProperty("cancelServRetPath", txtConstanciasRetencionesCancelar.getText());

        properties.setProperty("tipoPersona", cboTipoPersona.getSelectedItem().toString());
        properties.setProperty("regimen", cboRegimen.getSelectedItem().toString());

        properties.setProperty("rutaCFD", txtRutaCFDs.getText());
    }

    public void loadCertInfo() throws IOException {
        // Configuracion certificado
        txtRutaCertificado.setText(properties.getProperty("cerPath"));
        txtRutaLlave.setText(properties.getProperty("keyPath"));
        txtContrasenaLlave.setText(properties.getProperty("keyPass"));

        //Configuracion de servicio timbrado
        txtDireccionServicio.setText(properties.getProperty("servCfdiPath"));
        txtConstanciasRetenciones.setText(properties.getProperty("servRetPath"));
        txtUsuarioWsTimbrado.setText(properties.getProperty("servCfdiUser"));
        txtContrasenaToken.setText(properties.getProperty("servCfdiPass"));

        boolean cancelar = Boolean.parseBoolean(properties.getProperty("cancelCfdiSat"));
        chkCancelarSAT.setSelected(cancelar);
        txtDireccionServicioCancelar.setText(properties.getProperty("cancelServCfdiPath"));
        txtConstanciasRetencionesCancelar.setText(properties.getProperty("cancelServRetPath"));

        //Configuracion regimen fiscal
        cboTipoPersona.setSelectedItem(properties.getProperty("tipoPersona"));
        cboRegimen.setSelectedItem(properties.getProperty("regimen"));

        //Configuracion CFD
        boolean nuevaRutaCFD = Boolean.parseBoolean(properties.getProperty("chkRutaCFD"));
        chkRutaCFD.setSelected(nuevaRutaCFD);
        txtRutaCFDs.setEnabled(nuevaRutaCFD);
        btnExaminarRutaCFDs.setEnabled(nuevaRutaCFD);
        txtRutaCFDs.setText(properties.getProperty("rutaCFD"));

        // Info certificado
        X509Certificate cert = KeyLoaderFactory.createInstance(
                KeyLoaderEnumeration.PUBLIC_KEY_LOADER,
                new FileInputStream(properties.getProperty("cerPath"))
        ).getKey();

        byte[] byteArray = cert.getSerialNumber().toByteArray();
        lblNumeroSerie.setText(new String(byteArray));

        X500Name x500name = new X500Name(cert.getSubjectX500Principal().getName());
        X500Name x500nameIssuer = new X500Name(cert.getIssuerX500Principal().getName());
        lblEnviadoA.setText(x500name.getCommonName());
        lblEmitidoPor.setText(x500nameIssuer.getCommonName());
        lblVigencia.setText(new SimpleDateFormat("dd/MM/yyyy").format(cert.getNotBefore()) + " al " + new SimpleDateFormat("dd/MM/yyyy").format(cert.getNotAfter()));
    }

    public void checkExistsProperties() {
        try {
            String rutaPropiedades = System.getenv("APPDATA") + "\\Invoices\\Properties\\";
            String ficheroPropiedades = "config.properties";
            File folderPropiedades = new File(rutaPropiedades);
            File ficheroDest = new File(rutaPropiedades + ficheroPropiedades);

            if (!ficheroDest.exists()) {
                folderPropiedades.mkdirs();
                File ficheroFuente = new File("config.properties");
                FileInputStream in = new FileInputStream(ficheroFuente);
                FileOutputStream out = new FileOutputStream(ficheroDest);

                int c;
                while ((c = in.read()) != -1) {
                    out.write(c);
                }

                in.close();
                out.close();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdministration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdministration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdministration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdministration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        JFrame v = new JFrame();
//        v.addWindowListener(new WindowAdapter() {
//            public void windowOpened(WindowEvent e) {
//               
//            }
//        });
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdministration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExaminarCertificado;
    private javax.swing.JButton btnExaminarLlave;
    private javax.swing.JButton btnExaminarRutaCFDs;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnProbarConexion;
    private javax.swing.JButton btnProbarConexionBD;
    private javax.swing.JButton btnProbarConexionCancelar;
    private javax.swing.JComboBox cboRegimen;
    private javax.swing.JComboBox cboTipoPersona;
    private javax.swing.JCheckBox chkCancelarSAT;
    private javax.swing.JCheckBox chkRutaCFD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblEmitidoPor;
    private javax.swing.JLabel lblEnviadoA;
    private javax.swing.JLabel lblNumeroSerie;
    private javax.swing.JLabel lblVigencia;
    private javax.swing.JPanel pnlComprobantes;
    private javax.swing.JPanel pnlOrigenDatos;
    private javax.swing.JTabbedPane tabPanelPrincipal;
    private javax.swing.JTextField txtBaseDatos;
    private javax.swing.JTextField txtConstanciasRetenciones;
    private javax.swing.JTextField txtConstanciasRetencionesCancelar;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JPasswordField txtContrasenaLlave;
    private javax.swing.JPasswordField txtContrasenaToken;
    private javax.swing.JTextField txtDireccionServicio;
    private javax.swing.JTextField txtDireccionServicioCancelar;
    private javax.swing.JTextField txtInstancia;
    private javax.swing.JTextField txtRutaCFDs;
    private javax.swing.JTextField txtRutaCertificado;
    private javax.swing.JTextField txtRutaLlave;
    private javax.swing.JTextField txtServidor;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarioWsTimbrado;
    // End of variables declaration//GEN-END:variables
}
